### ISSUE TITLE
missing path in /etc/cron.d/alternc-sympa

### ISSUE THREAD

**Issue by sachaz** [AlternC/alternc-sympa#2]
Hi,

I got this cron error: 

`
Cron [root@SERVER](mailto:root@SERVER) /usr/lib/alternc/update_sympa.sh
sh: postmap: command not found
`

Please add to /etc/cron.d/alternc-sympa:
`PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin`

**Comment by camlafit** [comment]
Hello

As PATH is yet set with standard path, should be find by default.
PATH is it correctly set in your server ?

**Comment by sachaz** [comment]
cron runs jobs are from a non-interactive, non-login shell, environment variables doesn't rule there

**Comment by camlafit** [comment]
Hello

Following https://salsa.debian.org/debian/cron/-/blob/master/pathnames.h?ref_type=heads#L80 
by default we must at least have /usr/bin:/bin"

But if set in /etc/cron.[daily|weekly|monthly]  path could contain /usr/local and /usr/sbin/
https://salsa.debian.org/debian/cron/-/blob/master/debian/crontab.main

but with cron.d default PATH is maintained.

In this case as postmap is set in /usr/sbin/ and as explain in main we must declare full PATH value

**Comment by sachaz** [comment]
thx !
